import re

from scripts import demo_script

DOC = demo_script.OUT


def test_demo_script_is_generated_and_complete():
    text = DOC.read_text(encoding="utf-8")
    assert "Generated by `python -m scripts.demo_script`" in text
    rows = [line for line in text.splitlines() if re.match(r"^\| \d:\d\d", line)]
    assert len(rows) == 9  # every beat of plot.md §5
    assert "৳-" not in text and "Reconciled" in text


def test_money_format_matches_the_screens():
    assert demo_script.money(2207073) == "৳22,07,073"
    assert demo_script.money(-10876) == "−৳10,876"
    assert demo_script.money(25) == "৳25"
