"""Generate docs/data_report.md for Profiles A and B.

Usage (from backend/):  .venv/Scripts/python.exe -m data.report
"""

from __future__ import annotations

from dataclasses import asdict
from pathlib import Path

import pandas as pd

from app.config import BACKEND_DIR, get_settings
from data import checks
from data.generator import PROFILES, generate

REPORT_PATH = BACKEND_DIR.parent / "docs" / "data_report.md"


def _pct(x: float) -> str:
    return f"{x:.1%}"


def _parameter_diff() -> list[str]:
    a, b = asdict(PROFILES["A"]), asdict(PROFILES["B"])
    lines = ["| Parameter | Profile A | Profile B |", "|---|---|---|"]
    for key in a:
        if key != "name" and a[key] != b[key]:
            lines.append(f"| `{key}` | {a[key]} | {b[key]} |")
    return lines


def _salary_table(worlds: dict) -> list[str]:
    lines = ["| Industry | A median | B median |", "|---|---|---|"]
    medians = {}
    for name, t in worlds.items():
        emp = t["employees"].merge(t["employers"][["employer_id", "industry"]], on="employer_id")
        medians[name] = emp.groupby("industry")["salary_bdt"].median()
    for industry in sorted(medians["A"].index):
        lines.append(f"| {industry} | {medians['A'][industry]:,.0f} | {medians['B'].get(industry, float('nan')):,.0f} |")
    return lines


def build_report(seed: int) -> str:
    worlds = {name: generate(name, seed=seed) for name in ("A", "B")}
    out = [
        "# Data Report",
        "",
        f"Generated by `python -m data.report` with seed {seed}. Do not edit by hand. All data is synthetic.",
        "Profile A is the training world (stored in `seed.db`). Profile B is a held-out stress world, generated in memory and never used for training.",
        "",
        "## 1. What differs between A and B",
        "",
        *_parameter_diff(),
        "",
        "## 2. Table sizes",
        "",
        "| Table | A | B |",
        "|---|---|---|",
    ]
    for table in worlds["A"]:
        if table != "meta":
            out.append(f"| {table} | {len(worlds['A'][table]):,} | {len(worlds['B'][table]):,} |")

    out += ["", "## 3. Key distributions", "", "### Median monthly salary (BDT)", "", *_salary_table(worlds), ""]

    out += ["### Payroll run status", "", "| Status | A | B |", "|---|---|---|"]
    status = {n: t["payroll_runs"]["status"].value_counts(normalize=True) for n, t in worlds.items()}
    for s in ("on_time", "late", "partial", "default"):
        out.append(f"| {s} | {_pct(status['A'].get(s, 0))} | {_pct(status['B'].get(s, 0))} |")

    out += ["", "### Advance outcomes", "", "| Measure | A | B |", "|---|---|---|"]
    summary = {n: checks.outcome_summary(t) for n, t in worlds.items()}
    out.append(f"| Advances | {summary['A']['advances']:,} | {summary['B']['advances']:,} |")
    for key, label in (
        ("approval_rate", "Approval rate (pilot rules)"),
        ("failure_rate", "Not recovered by due date + grace"),
        ("loss_rate_by_amount", "Loss as share of money due"),
    ):
        out.append(f"| {label} | {_pct(summary['A'][key])} | {_pct(summary['B'][key])} |")
    causes = sorted(set(summary["A"]["loss_causes"]) | set(summary["B"]["loss_causes"]))
    for cause in causes:
        out.append(f"| Advances lost: {cause} | {summary['A']['loss_causes'].get(cause, 0)} | {summary['B']['loss_causes'].get(cause, 0)} |")

    out += ["", "## 4. Pattern checks", "", "| Check | A | B |", "|---|---|---|"]
    results = {n: checks.pattern_checks(t, PROFILES[n]) for n, t in worlds.items()}
    for ca, cb in zip(results["A"], results["B"]):
        out.append(
            f"| {ca.name} | {'PASS' if ca.passed else 'FAIL'}: {ca.detail} | {'PASS' if cb.passed else 'FAIL'}: {cb.detail} |"
        )
    out.append("")
    return "\n".join(out)


def main() -> None:
    REPORT_PATH.write_text(build_report(get_settings().seed), encoding="utf-8")
    print(f"wrote {REPORT_PATH}")


if __name__ == "__main__":
    pd.set_option("display.width", 120)
    main()
